### ISSUE TITLE
FastaFile.rev_seq fail to complement for lower case input

### ISSUE THREAD

**Issue by s6juncheng** [huangyh09/brie#10]
Hi Yuanhua,

there is a potential bug in FastaFile.rev_seq() function:

```
rev_seq("atgc")
>>> 'cgta'
```
Some parts of the reference fasta file has lower case letters (repetitive regions), in which case it will be a bug.
A possible better option will be 
```
def rev_seq(seq):
    complement = {'A': 'T', 'C': 'G', 'G': 'C', 'T': 'A', "N": "N"}
    return '"".join([complement[base] for base in seq.upper()[::-1]])
```
Best,
Jun

**Comment by huangyh09** [comment]
Hi Jun,

Many thanks for the kind suggestion. Just fixed this bug.

best,
YH
