### ISSUE TITLE
Data Interpretation

### ISSUE THREAD

**Issue by JustRoomTemp** [huangyh09/brie#14]
Hi all,

I'm an undergraduate research assistant who was asked to figure out how to install and use BRIE and BRIE-kit for my research lab, but as I am in no way a trained statistician, I have no clue where to start interpreting the brie-diff output.

If unclear, I'm referring to the ~.diff.tsv file and ~.diff.rank.tsv file that are both created after running the program. My data, for example, looks like this:

<img width="1101" alt="screen shot 2018-06-19 at 1 27 17 pm" src="https://user-images.githubusercontent.com/40402135/41613766-845b8078-73c4-11e8-8d8e-832ee5a186ac.png">

What can I do to visualize and understand these results?

Edit - I can access each column individually or in comparison in a program like RStudio, but without an understanding of statistics behind BRIE, I cannot use the data

**Comment by huangyh09** [comment]
Hi,

Thanks for the question, and using BRIE. In the manual (https://brie-rna.sourceforge.io/manual.html#differential-splicing), we briefly described the meaning of these 15 columns in `xx.diff.tsv `. 

Essentially, BRIE aims to quantify the fraction of isoform with exon included, which is a unknown variable and we want to estimate from the RNA-seq reads. However, when we have very limited reads, e.g., in single cells, we won't be very confident. In BRIE, we give the mean estimate and the 95% confidence interval. 

When compare a splicing event between two cells, we used Bayes factor, which the higher the more likely two cells are different. For using, we suggest to use Bayes factor to filter differential splicing. In addition, you could also use the 95% confidence interval (e.g., <0.25) and number of reads (e.g., > 3) as a more stringent threshold. 

Hope these help, but I do suggest reading our paper and manual. 

Yuanhua
