### ISSUE TITLE
What's the difference between mouse_features.filtered.csv.gz and mouse_features.lenient.csv.gz, and which one to use?

### ISSUE THREAD

**Issue by gangcai** [huangyh09/brie#17]
Hi Yuanhua,
      For the parameter "-f" in brie, which feature file should I use?  The lenient or filtered? Is "-f" parameter optional or must needed?

Thanks,
Gangcai

**Comment by RuyBlast** [comment]
Hi Gangcai,
I worked on BRIE, I do not know where you found your two feature files, but I can tell you that -f is a needed argument for BRIE. You can generate your feature file thanks to brie-factor from briekit. But if you want to try quickly, I think from their names that you could use one or the other of your feature files (I would use the filtered one).
Best,
Milan

**Comment by gangcai** [comment]
Hi Milan,
      Thanks for your reply. Those two files were generated by briekit-factor according to this script provided by Brie https://github.com/huangyh09/briekit/blob/master/example/anno_mouse.sh.  The names indicated in the script are mouse_factors.SE.filtered.csv.gz and mouse_factors.SE.lenient.csv.gz respectively.  Do you have any suggestion about in which scenario should I use filtered and when to use lenient?

Best,
Gangcai

**Comment by huangyh09** [comment]
Hi Gangcai,

These two files are according to the Splicing event annotation: SE.filtered.gff3.gz and SE.lenient.gff3.gz. The former is stricter while the latter is more lenient on the length of alternative exon and the distance between TSS or TTS. Normally, I would recommand using SE.filtered.gff3.gz, but if it doesn't include the events you are interested in, then you could use the lenient one or add it manually.

Best,
Yuanhua
