### ISSUE TITLE
Error in map_data function

### ISSUE THREAD

**Issue by cmarti** [huangyh09/brie#25]
Hi, 

I have been trying to use BRIE for a couple of days and running into errors when trying to quantify splicing rates following the manual. In particular I was getting an error in the MH_heuristic function because idxF was empty. I have tracked down this to the map_data function:

"elif ids[idx1[i]] == tran_ids[idx2[j]]:"

this basically never happens because of the suffixes you add to the ids. I have modified my version to remove the suffixes but I am not sure this is how it should be done. Anyway, have a look please and see if you can fix it.

Thanks!

**Comment by cmarti** [comment]
I sorted it out. Apparently the event filtering step changes the format of the annotation file and only the new GTF format is compatible with the downstream BRIE analysis. It is a bit confusing though, I would expect to have the same formats along the pipeline.

**Comment by huangyh09** [comment]
Hi, 
Thanks for updating and good to hear it is sorted. This confusing issue will be taken into account and hopefully sorted in new release.
Thanks
Yuanhua
