### ISSUE TITLE
Export count matrix containing isoforms

### ISSUE THREAD

**Issue by grimwoo** [huangyh09/brie#30]
After finishing the ```brie```, I had three files: fractions.tsv, weights.tsv and samples.csv.gz.
And I need to use [Seurat](https://github.com/satijalab/seurat) for further analysis.
However, I need, at least, the expression matrix. The format could be as following:
```
                                 AAACATACCATCAG AAACATACCGATAC AAACATACGCATCA
ENSMUSG00000111425.1               1             2              0
ENSMUSG00000024442.5               0             1              0
```
OR
```
                           Cell_1     Cell_2    Cell_3
Gene_1_isoform_1               1          2          0
Gene_1_isoform_2               0          1          0
Gene_2_isoform_1               1          1          0
```
Does anyone know how to export a file like this or how to combine BRIE and Seurat?

**Comment by huangyh09** [comment]
Hi, Sorry on the delay. It is not straightforward to get the isoform-by-cell matrix in BRIE1, but it should be properly supported in BRIE2 (in AnnData layer).

Yuanhua
