### ISSUE TITLE
Modeling cell-level technical variation

### ISSUE THREAD

**Issue by gmstanle** [huangyh09/brie#35]
I was wondering if there's any way to include cell technical variation (e.g., # of genes detected, percent mitochondrial, or read depth). These often have considerable impact on gene expression estimation but are not really biological.

**Comment by huangyh09** [comment]
Yes, you can include these technical factors as covariate(s) in the cell features (i.e., design matrix). 
We also include the cell detection rate (cdr) as technical factor in the dentate Gyrus data (see the [command line](https://github.com/huangyh09/brie-tutorials/blob/main/dentateGyrus/run_brie2.sh#L31)).

But, in general Psi is a proportional value and self-normalised, so will be much less affected by technical variation between cells, comparing to gene level expression.

Yuanhua
