### ISSUE TITLE
the output of brie-count has not .h5ad file

### ISSUE THREAD

**Issue by liuyu988** [huangyh09/brie#46]
Hi Yuanhua,

my code is as follows:
> brie-count -a genes.gff3  -S cell.bam -b barcodes.tsv.gz -o test2/ -p 15 -t any

this process ran for 15 hours, however, the result files don't contain the improtant .h5ad file.

Is anything i miss? thanks

**Comment by huangyh09** [comment]
it looks the same as issue #47, so I close here.
