### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by yang91** [huangyh09/brie#6]
Hi,

I've met error when installating brie, no matter using 'pip install' or downloading brie packages and using 'python setup.py install'.

```
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    import brie
  File "/home/yangxx/software/brie-v0.1.3/brie/__init__.py", line 8, in <module>
    from .utils.bias_utils import FastaFile, BiasFile
  File "/home/yangxx/software/brie-v0.1.3/brie/utils/bias_utils.py", line 6, in <module>
    import pylab as pl
ImportError: No module named pylab
```

I've tried to fink 'pylab' packages in PYPI but no package have the name exactly same as 'pylab'. My python version 2.7.12. Do you have any idea about this issue?

**Comment by huangyh09** [comment]
Hi,

Thanks for using BRIE, and getting in touch.

The problem here is from the pylab package, which is probably not an independent library. I have turned this function off in the latest GitHub repo. 

Please download and install it again. Let me know if you find any error. 

Best wishes,
Yuanhua

**Comment by yang91** [comment]
Oh yes, this modification made installation successfully. Now it's all right, I'll keep in touch if another error are produced in future. Thank you for your kindly help :)
